---
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` file in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    reviewers:
      - "elastic/apm-agent-rum"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "weekly"
    reviewers:
      - "elastic/apm-agent-rum"
