#!/usr/bin/env groovy
@Library('apm@current') _

opbeansPipeline(builds: ['apm-agent-dotnet/opbeans-dotnet-mbp/master',
                         'apm-agent-go/opbeans-go-mbp/master',
                         'apm-agent-java/opbeans-java-mbp/master',
                         'apm-agent-nodejs/opbeans-node-mbp/master',
                         'apm-agent-python/opbeans-python-mbp/master',
                         'apm-agent-ruby/opbeans-ruby-mbp/master'])
