---
## Workflow to periodically check if there is an available newer APM agent version, e.g.
## "1.2.3". If so, then update to it and tag this repo with that version, e.g.
## "v1.2.3".
name: bump-version

on:
  workflow_dispatch: ~
  schedule:
    - cron:  '0 20 * * 6'

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'
      - uses: elastic/apm-pipeline-library/.github/actions/updatecli@current
        with:
          vaultUrl: ${{ secrets.VAULT_ADDR }}
          vaultRoleId: ${{ secrets.VAULT_ROLE_ID }}
          vaultSecretId: ${{ secrets.VAULT_SECRET_ID }}
          pipeline: ./.ci/bump-version.yml
