---
## Workflow to periodically check if there is an available newer APM agent version, e.g.
## "1.2.3". If so, then update to it and tag this repo with that version, e.g.
## "v1.2.3".
name: bump-version

on:
  workflow_dispatch: ~
  schedule:
    - cron:  '0 20 * * 6'

permissions:
  contents: read

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Get token
        id: get_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.OBS_AUTOMATION_APP_ID }}
          private-key: ${{ secrets.OBS_AUTOMATION_APP_PEM }}
          permissions-contents: write
          permissions-pull-requests: write

      - uses: elastic/oblt-actions/updatecli/run@v1
        with:
          command: "--experimental apply --config .ci/bump-version.yml"
        env:
          GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}

      - if: failure()
        uses: elastic/oblt-actions/slack/send@v1
        with:
          bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel-id: "#apm-agent-js"
          message: ":traffic_cone: updatecli failed for `${{ github.repository }}@${{ github.ref_name }}`, @robots-ci please look what's going on <https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|here>"
