---
# Takes the version of elastic-apm in the requirements.txt file and creates a tag
# if the tag does not exist yet.
name: create-tag

on:
  push:
    branches:
      - main
    paths:
      - package.json

permissions:
  contents: write

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # also fetch tags
      - run: |
          ELASTIC_APM_VERSION="$(grep 'elastic/apm-rum"' package.json | cut -d":" -f2 | sed 's# "##g' | sed 's#",##g')"
          # if the tag does not exist
          if [[ ! $(git tag -l "${ELASTIC_APM_VERSION}") ]]; then
            git tag ${ELASTIC_APM_VERSION}
            git push origin "refs/tags/${ELASTIC_APM_VERSION}"
          fi
